# Dependabot 版本更新配置  
# 详细配置选项请参见：  
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file  

version: 2  
updates:  
  - package-ecosystem: "pip"  # 使用 pip 作为包管理系统  
    directory: "/"  # 包清单文件的位置  
    schedule:  
      interval: "weekly"  # 每周检查更新  
    allow:  
      # 允许更新直接依赖和间接依赖  
      - dependency-type: "all"  
    # 可选：忽略某些更新  
    # ignore:  
    #   - dependency-name: "some-package"  
    #     versions: ["1.x", "2.x"]  
