version: '3.8'  

services:  
  app:  
    build:   
      context: .  
      dockerfile: Dockerfile.base  # 指定 Dockerfile  
    ports:  
      - "8000:8000"  
    volumes:  
      - .:/app  # 挂载当前目录为容器内的 /app  
    environment:  
      - DOCKER_ENV=1  # 如果您的应用需要特定的环境变量  
    tty: true  
    stdin_open: true